name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to K8s Cluster
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        shell: powershell
        run: Set-Content -Path kubeconfig -Value $env:KUBECONFIG_CONTENT -Encoding Ascii
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          KUBECONFIG: kubeconfig

      - name: Replace placeholders in vehicle-deployment.yaml
        shell: powershell
        run: |
          (Get-Content k8s/vehicle/vehicle-deployment.yaml) `
          -replace '\$\{\{ secrets\.DOCKER_USERNAME \}\}', '${{ secrets.DOCKER_USERNAME }}' `
          | ForEach-Object { $_ -replace '\$\{\{ github\.sha \}\}', '${{ github.sha }}' } `
          | Set-Content k8s/vehicle/vehicle-deployment.yaml
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
          KUBECONFIG: kubeconfig

      - name: Create and apply Postgres Secret
        shell: powershell
        run: |
          kubectl create secret generic postgres-secret `
            --from-literal=username=${{ secrets.POSTGRES_USERNAME }} `
            --from-literal=password=${{ secrets.POSTGRES_PASSWORD }} `
            --dry-run=client -o yaml --validate=false `
            | kubectl apply -f - --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Deploy Postgres manifests
        shell: powershell
        run: kubectl apply -f k8s/postgres/ --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Deploy Vehicle Service manifests
        shell: powershell
        run: kubectl apply -f k8s/vehicle/ --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Restart Deployment
        shell: powershell
        run: kubectl rollout restart deployment vehicle-service
        env:
          KUBECONFIG: kubeconfig
