name: CD to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to K8s Cluster
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        shell: pwsh
        run: $env:KUBECONFIG_CONTENT | Out-File -FilePath kubeconfig -Encoding ascii
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          KUBECONFIG: kubeconfig

      - name: Create and apply Postgres Secret
        shell: pwsh
        run: |
          $env:KUBECONFIG_CONTENT | Out-File -FilePath kubeconfig -Encoding ascii
          kubectl create secret generic postgres-secret `
            --from-literal=username=${{ secrets.POSTGRES_USERNAME }} `
            --from-literal=password=${{ secrets.POSTGRES_PASSWORD }} `
            --dry-run=client -o yaml --validate=false `
            | kubectl apply -f - --validate=false
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          KUBECONFIG: kubeconfig

      - name: Deploy Postgres manifests
        shell: pwsh
        run: kubectl apply -f k8s/postgres/ --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Deploy Vehicle Service manifests
        shell: pwsh
        run: kubectl apply -f k8s/vehicle/ --validate=false
        env:
          KUBECONFIG: kubeconfig
